version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/library"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "library dependencies"
#  - package-ecosystem: "gradle"
#    directory: "/docker"
#    schedule:
#      interval: "weekly"
#    target-branch: "main"
#    labels:
#      - "toolkit dependencies"
#  - package-ecosystem: "docker"
#    directory: "/docker"
#    schedule:
#      interval: "weekly"
#    target-branch: "main"
#    labels:
#      - "docker dependencies"
#  - package-ecosystem: "gradle"
#    directory: "/spark"
#    schedule:
#      interval: "weekly"
#    target-branch: "main"
#    labels:
#      - "spark dependencies"
